name: GitHub Actions Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: windows-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
